language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t luo39/docker-react -f Dockerfile.dev .

scripts:
  - docker run luo39/docker-react npm run test -- --coverage