language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t luo39/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true luo39/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-001609791934"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY